# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
