# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161104_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=b'Null Content', max_length=200)),
            ],
            options={
                'db_table': 'citation',
            },
        ),
    ]
